# Kitty tmux integration
set -g default-terminal "xterm-kitty"
set -g terminal-overrides ',xterm-kitty:RGB'

# Enable kitten images
set -g @kitten-enabled 1
set -g @kitten-images "on"
set -g @kitten-image-background "on"
set -g @kitten-image-method "auto"

# Allow passthrough for graphics
set -g allow-passthrough on
